import type { Metadata } from "next";
import { Ubuntu, Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const geistSans = Ubuntu({
  variable: "--font-ubuntu-sans",
  weight: ["300", "400", "500", "700"], // Usar 300 light, 400 regular, 500 medium, 700 bold
  subsets: ["latin"],
});

const geistMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  weight: ["400", "700"], // Usar 400 regular, 700 bold
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by Sebaxtian",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
